### PR TITLE
Porting Presto UDFs for Presto 0.193

### PR DESCRIPTION
**Pull request by amoghmargoor**
PR is for porting udfs to QDS Presto 0.193.

@stagraqubole we would also need to release a jar before merging this PR I guess. If you can do it then its fine, otherwise i can release it to sonatype using qubole account.

### CODE REVIEW

**Comment by shubhamtagra** [comment]
Is this tested to work in 0.193? I mean not just compile, the functions execute fine?

You can go ahead with a release independently, do update the README via that change or this to show the highest version that supports 0.180

**Comment by amoghmargoor** [comment]
@stagraqubole oh this has been tested ...basic sanity for all functions have been done. PR title was deceptive though - have changed it. will make release for 180.

**Review by shubhamtagra — APPROVED** [review]

**Comment by amoghmargoor** [comment]
@stagraqubole looks like i don't have write permissions to the repo. So I could not release jars as it tries to checking in the pom file commits and fails.

**Comment by shubhamtagra** [comment]
Released 2.0.2

Please merge master and update readme to put 2.0.2 against 0.180 and add new row for 0.193

**Comment by amoghmargoor** [comment]
@stagraqubole done rebasing with master and updating README.

**Review by shubhamtagra — APPROVED** [review]
lgtm

**Comment by shubhamtagra** [comment]
Merged 890b6ab3da7d7b426c16d8f864a2dbd7e4f2d285

**Pull request closed without merging**
