### PR TITLE
new:usr:#3:Change package name. Set independent version to project

### PR DESCRIPTION
**Pull request by vrajat**
This commit changes the namespace to com.qubole.presto.udfs.
Also it sets the version to 0.1.0-SNAPSHOT. Setting the version required major
surgery of pom.xml file. I had to move dependencies from provided to a particular
version.

### CODE REVIEW

**Comment by shubhamtagra** [comment]
UdfFactory needs an update, it registers methods using namespace

**Comment by vrajat** [comment]
@stagraqubole this PR is now tested. I ran a query which used the udfs. Server logs for reference:

```
2016-06-30T23:09:00.988Z        INFO    main    com.qubole.presto.udfs.UdfFactory       Adding: class com.qubole.presto.udfs.UdfPlugin
2016-06-30T23:09:00.989Z        INFO    main    com.qubole.presto.udfs.UdfFactory       Adding: class com.qubole.presto.udfs.window.FirstOrLastValueIgnoreNullFunction$1
2016-06-30T23:09:00.989Z        INFO    main    com.qubole.presto.udfs.UdfFactory       Adding: class com.qubole.presto.udfs.window.FirstOrLastValueIgnoreNullFunction
2016-06-30T23:09:00.989Z        INFO    main    com.qubole.presto.udfs.UdfFactory       Adding: class com.qubole.presto.udfs.window.DoubleFirstValueIgnoreNullFunction
2016-06-30T23:09:00.989Z        INFO    main    com.qubole.presto.udfs.UdfFactory       Adding: class com.qubole.presto.udfs.window.FirstOrLastValueIgnoreNullFunction$Direction
2016-06-30T23:09:00.989Z        INFO    main    com.qubole.presto.udfs.UdfFactory       Adding: class com.qubole.presto.udfs.window.DoubleLastValueIgnoreNullFunction
2016-06-30T23:09:00.989Z        INFO    main    com.qubole.presto.udfs.UdfFactory       Adding: class com.qubole.presto.udfs.window.BooleanLastValueIgnoreNullFunction
2016-06-30T23:09:00.989Z        INFO    main    com.qubole.presto.udfs.UdfFactory       Adding: class com.qubole.presto.udfs.window.VarcharLastValueIgnoreNullFunction
2016-06-30T23:09:00.989Z        INFO    main    com.qubole.presto.udfs.UdfFactory       Adding: class com.qubole.presto.udfs.window.BigintLastValueIgnoreNullFunction
2016-06-30T23:09:00.990Z        INFO    main    com.qubole.presto.udfs.UdfFactory       Adding: class com.qubole.presto.udfs.window.BigintFirstValueIgnoreNullFunction
2016-06-30T23:09:00.990Z        INFO    main    com.qubole.presto.udfs.UdfFactory       Adding: class com.qubole.presto.udfs.window.VarcharFirstValueIgnoreNullFunction
2016-06-30T23:09:00.990Z        INFO    main    com.qubole.presto.udfs.UdfFactory       Adding: class com.qubole.presto.udfs.window.BooleanFirstValueIgnoreNullFunction
2016-06-30T23:09:00.990Z        INFO    main    com.qubole.presto.udfs.UdfFactory       Adding: class com.qubole.presto.udfs.aggregation.ArrayAggregation
2016-06-30T23:09:00.990Z        INFO    main    com.qubole.presto.udfs.UdfFactory       Adding: class com.qubole.presto.udfs.aggregation.state.ArrayAggregationStateFactory$SingleArrayAggregationState
2016-06-30T23:09:00.990Z        INFO    main    com.qubole.presto.udfs.UdfFactory       Adding: class com.qubole.presto.udfs.aggregation.state.ArrayAggregationStateFactory$GroupedArrayAggregationState
2016-06-30T23:09:00.990Z        INFO    main    com.qubole.presto.udfs.UdfFactory       Adding: interface com.qubole.presto.udfs.aggregation.state.ArrayAggregationState
2016-06-30T23:09:00.990Z        INFO    main    com.qubole.presto.udfs.UdfFactory       Adding: class com.qubole.presto.udfs.aggregation.state.ArrayAggregationStateSerializer
2016-06-30T23:09:00.990Z        INFO    main    com.qubole.presto.udfs.UdfFactory       Adding: class com.qubole.presto.udfs.aggregation.state.ArrayAggregationStateFactory
2016-06-30T23:09:00.990Z        INFO    main    com.qubole.presto.udfs.UdfFactory       Adding: interface com.qubole.presto.udfs.WindowFunctionDefinition
2016-06-30T23:09:00.990Z        INFO    main    com.qubole.presto.udfs.UdfFactory       Adding: class com.qubole.presto.udfs.UdfFactory
2016-06-30T23:09:00.990Z        INFO    main    com.qubole.presto.udfs.UdfFactory       Adding: class com.qubole.presto.udfs.scalar.ExtendedMathFunctions
 2016-06-30T23:09:00.991Z        INFO    main    com.qubole.presto.udfs.UdfFactory       Could not add com.qubole.presto.udfs.scalar.ExtendedMathFunctions, exception: java.lang.IllegalArgumentException: Expected class com.qubole.presto.udfs.scalar.ExtendedMathFunctions to contain at least one method annotated with @ScalarFunction, stack: [Ljava.lang.StackTraceElement;@3c27f72
2016-06-30T23:09:00.991Z        INFO    main    com.qubole.presto.udfs.UdfFactory       Adding: class com.qubole.presto.udfs.scalar.hiveUdfs.ExtendedDateTimeFunctions
2016-06-30T23:09:00.997Z        INFO    main    com.qubole.presto.udfs.UdfFactory       Adding: class com.qubole.presto.udfs.scalar.NumberSystemFunctions
```

**Comment by vrajat** [comment]
I meant _now_ tested.

**Comment by vrajat** [comment]
If everything looks OK, please squash merge and use the title (so that we can use gitchangelog to generate release notes) & description from my first commit. Also check https://help.github.com/articles/closing-issues-via-commit-messages/

**Pull request merged**
